config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web =>"/sidekiq"
  devise_for :users
  root "articles#index"
  resources :articles do
  resources :comments
  
    # collection do 
    #   get 'search'
  get 'search',to: "articles#search"
  #get '/search' => 'articles#search', :as => 'search_page'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :pictures, :as => :imageable, :dependent => :destroy
  accepts_nested_attributes_for :pictures, :allow_destroy => true
  validates :Tittle, presence: true
  validates :description, presence: true, length: { minimum: 10 }
 
  def self.search(search)
  if search
    where('name LIKE ?', "%#{search}%")
  else
    all
  end
end  
 
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user
  has_many :pictures, :as => :imageable, :dependent => :destroy
  accepts_nested_attributes_for :pictures, :allow_destroy => true
#   validates :rating, presence: true
  #validates :description, presence: true, length: { minimum: 10 }
end

app/models/picture.rb
class Picture < ApplicationRecord
 belongs_to :imageable, :polymorphic => true
 has_attached_file :image, styles: { medium: "150*150>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
 validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :articles
  has_many :comments

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 #config.active_job.queue_adapter = :sidekiq
  before_action :authenticate_user!
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
 before_action :authenticate_user!, except: [:index, :show]
  before_action :author, only: [:edit, :update, :destroy]
  def index
     if params[:search_key]
      @articles = Article.where("Tittle LIKE ? OR description LIKE ?","%#{params[:search_key]}%", "%#{params[:search_key]}%").paginate(:page => params[:page], :per_page => 4)
    else
      @articles = Article.paginate(:page => params[:page], :per_page => 4)
    end 
  end
  def show
    @article = Article.find(params[:id])
    if @article.blank?
      @average_comment = 0
    else
      @average_comment = Comment.where(article_id: @article.id).average(:rating)
    end
  end

  def new
    @article = current_user.articles.build
    #@article.picture.build
  end

  def create
    @article = current_user.articles.build(article_params)
    if @article.save
      FilterJob.perform_later(@article.id)
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
   
  end

  def update
    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
   
    @article.destroy
    redirect_to root_path
  end
  def author
   
    redirect_to articles_path, notice: "Not Authorized To Edit This Article" unless @article.user_id==current_user.id
      
  end

private
  def article_params

   params.require(:article).permit(:user_id, :Tittle, :description, pictures_attributes: [:id , :image, :_destroy])
  end

  def set_article
    @article = Article.find(params[:id])
  end
 end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
   before_action :find_article
   before_action :author, only: [:edit, :update, :destroy]
   skip_before_action :verify_authenticity_token, only: [:create]
def index
  @comment = Comment.all
end

def show
  @comment = Comment.find(params[:id])
end

  def new
  end
  def create
    @comment = @article.comments.build(comment_params)
    @comment.save
   flash[:success] = "Comment successfully added"
   respond_to do |format|
    format.js  { render :layout => false,  :locals => {comment: @comment}  }
     format.html { redirect_to article_path(@article)}    
    end
  end
 
  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    respond_to do |format|
     format.html { redirect_to article_path(@article)}    
      format.js   { render :layout => false,  :locals => {comment: @comment}  }   
     end
  end
 def author
   
    redirect_to articles_path, notice: "Not Authorized To Edit This Comment" unless @article.user_id==current_user.id
      
  end

  private
    def comment_params
     # params.require(:comment).permit( :rating, :description, :user_id,picture_attributes: [:id , :_destroy])
      params.require(:comment).permit( :rating, :description, :user_id,:pictures_attributes => [:id, :image, :_destroy])
    end

    def find_article
     @article = Article.find(params[:article_id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_articles.html.erb
<div class="row">

   <% articles.each do |article| %>
   <!-- here at articles.each we didn't write @articles because in index.html.erb we have already initialize it with  articles: @articles  -->

      <div class="col-md-3">
        <%article.pictures.each do |pic|  %>
        <%= image_tag pic.image.url(:medium) %>
      <% end %>
        <h3><%= link_to article.Tittle, article %></h3>
      </div>  

    <% end %>

  </div>
<h5><%= link_to "New Article", new_article_path ,class:"btn btn-custom"%></h5>





    <%= will_paginate @article %>

app/views/articles/_form.html.erb
<%= form_for @article, url: @article, html: { multipart: true } do |form| %>
  <div>
    <%= form.label :Tittle %><br>
    <%= form.text_field :Tittle %>
    <% article.errors.full_messages_for(:Tittle).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.label :description %><br>
    <%= form.text_area :description %><br>
    <% article.errors.full_messages_for(:description).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

   <div>
     <%= form.fields_for :pictures, form.object.pictures.build do |f| %>
        <!-- , form.object.picture -->
        <%= f.label :image %><br>
        <%= f.file_field :image%>
      <%end %>
  </div>
  <br>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<div class="col-md-6 col-md-offset-3">

  <div class="edit-book-form"><h1>Edit Article</h1>

<%= render "form", article: @article %>

  </div>

</div>

app/views/articles/index.html.erb
<h1>Articles</h1>
<div id="articles">
  
  <%= render 'articles', articles: @articles %>
   <!-- here articles(a variable that stores @articles): @articles  -->
</div>

app/views/articles/index.js.erb
$("#articles").html("<%= escape_javascript(render('articles', articles: @articles)) %>");
// here articles(a variable that stores @articles): @articles 

app/views/articles/new.html.erb
<div class="col-md-6 col-md-offset-3">

  <div class="new-book-form">  <h1>New Article</h1>
    <%= render "form", article: @article %>

  </div>

</div>

app/views/articles/show.html.erb
<div class="row">
  <div class="col-md-4" >
    <%@article.pictures.each do |pic|  %>
       <%= image_tag pic.image.url %>
    <% end %>
  </div>
  <div class="col-md-8">
    <div class="article-info">
      <h1 class="article-title"><%= @article.Tittle %></h1>
      <h3 class="article-author"><span>From</span> <%= @article.user.email %></h3>
      <p id="notice"><%= notice %></p>
      <div class="average-comment-rating" data-score=<%= @average_comment %>></div>
      <p class="article_desc"><%= @article.description %></p>
   </div>
   <div class="links btn-group">
  
    <% if @article.user_id == current_user.id %>
      
      <h4><%= link_to "Edit", edit_article_path(@article), class:"btn btn-custom"%>&nbsp&nbsp</h4> 
      <h4><%= link_to "Destroy", article_path(@article),class:"btn btn-custom",
                  method: :delete,
                  data: { confirm: "Are you sure?" } %></h4>
    <% end %>
 

</div>

  </div>
</div>

<!-- comment section start -->

<h2><br>Comments</h2>
<div id='com_ment'>
  <%= render @article.comments %>
</div>
<h2>Add a comment:</h2>
<%= render 'comments/form' %>


<script>
  $('.comment-rating').raty({
    readOnly: true,
    score: function() {
      return $('.comment-rating').attr('data-score');
    },
    path: '/assets/'
  });
</script>
<script>
  $('.average-comment-rating').raty({
    readOnly: true,
    path: '/assets/',
    score: function() {
      return $(this).attr('data-score')
    }
  });
</script>

<!-- <script>
  $('.average-comment-rating').raty({
     click: function(score, evt) {
    alert('ID: ' + this.id + "\nscore: " + score + "\nevent: " + evt);
  }
    }
  });
</script> -->

app/views/comments/_comment.html.erb
<div id="comment_<%= comment.id %>">
  <!-- <div class="col-md-4" > -->

    <% comment.pictures.each do |pic|  %>
      <%= image_tag pic.image.url%>
    <%end%>
  <!-- </div> -->

 <div id="comment-<%= comment.id %>">
  <div class="comment-rating" data-score="<%= comment.rating %>"></div>

  <p class="comments-description"><%= comment.description %></p>
  
<% if user_signed_in? %>
    <% if comment.user_id == current_user.id %>

      <div id="Destroy" class="links btn-group">
          <%= link_to 'Destroy Comment', [comment.article, comment], remote: true, class:"delete btn btn-custom",
              method: :delete,
              data: { confirm: "Are you sure?" } %>

      </div>
    
    <% end %> 
  <% end %>
</div>
</div>

app/views/comments/_form.html.erb
<%= form_for [ @article, @article.comments.build ], url: article_comments_path(@article), remote: true do |form| %>
 
    <div id="rating-form">
     <%= form.label :rating ,placeholder:"Rate the article"  %><br>
   
  </div>
<%= form.hidden_field :user_id, value: current_user.id %>
<p>
    <%= form.label :description %><br>
    <%= form.text_area :description , rows: 2, cols:30, placeholder:"Write a Comment..." %>
  </p>

  <p>
    <%= form.fields_for :pictures, form.object.pictures.build do |f| %>
        <%= f.label :image %><br>
        <%= f.file_field :image%>
    <%end %>
    
 </p> 

  <p>
     <%= form.submit 'Post comment', class:'button' %>
  </p>
  <% end %>


<script>
  $('#rating-form').raty({
    path: '/assets/',
    scoreName: 'comment[rating]'
  });
</script>

app/views/comments/create.js.erb
$('#com_ment').html("<%= escape_javascript(render @article.comments )%>");

app/views/comments/destroy.js.erb
$('#comment_<%= @comment.id %>').remove();

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%# debugger %>
    <%= render partial: "shared/navbar"%>
    <br>
    <div class="container">
      <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
<p id="notice"><%= notice %></p>
     <%= yield %> 
    </div>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
<script src="//code.jquery.com/jquery-1.11.2.min.js"></script>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "BLOG", root_path, class:"navbar-brand" %>
   
  <% if user_signed_in? %>
    <%= link_to "Add Article",new_article_path, class:"navbar-brand" %>
  
    <% end %>
      
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
    </div>
  </div>

  <p class="navbar-text float-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
</p>

  <div>
  
   <!-- search through JS request  -->

  <%= form_tag articles_path, method: :get, remote: true do %>
  <!-- by writing remote: true it will give the JS request not HTML request -->
<%= search_field_tag :search, params[:search],placeholder:"type something", class:"form-control", class: 'navbar-form navbar-left', name: "search_key"%>
<p>
  <%= submit_tag "search",  :class => 'btn btn-info glyphicon glyphicon-search',:Tittle=> nil %> 
</p>
<% end %>
  </div>
</nav>